name: deploy-action
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Install dependencies
        run: |
          sudo apt update &&
          sudo apt install -y \
            build-essential \
            musl-tools \
            pkg-config \
            libssl-dev

      - name: Build project
        env:
          GOARCH: amd64
          GOOS: linux
          CGO_ENABLED: 1
          CC: /usr/bin/musl-gcc
        run: |
          go build \
            -o auth-proxy-linux-amd64 \
            -ldflags "-s -w -linkmode external -extldflags -static" \
            -trimpath \
            -v \
            .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          files: |
            auth-proxy-linux-amd64
